#=========================================================================
# TravisCI Setup
#=========================================================================

#------------------------------------------------------------------------
# language and build matrix
#------------------------------------------------------------------------

dist: xenial
language: python
python:
 - "2.7"
 - "pypy"
 - "3.6"
 - "3.7"
 - "pypy3.5"

env:
 - CONFIG=""
 #- CONFIG="--test-verilog"
 # - CONFIG="--dump-vcd"

#------------------------------------------------------------------------
# install dependencies
#------------------------------------------------------------------------

install:

 # Install packages
 - sudo apt-get install -y graphviz

 # Install verilator
 - wget https://github.com/cornell-brg/verilator-travisci-cache/raw/master/verilator-travis-4.008.tar.gz
 - tar -C ${HOME} -xzf verilator-travis-4.008.tar.gz
 - export VERILATOR_ROOT=${HOME}/verilator
 - export PATH=${VERILATOR_ROOT}/bin:${PATH}
 - export PYMTL_VERILATOR_INCLUDE_DIR=${VERILATOR_ROOT}/share/verilator/include
 - verilator --version

 # Install Python requirements
 - pip install --upgrade pip setuptools twine
 - pip install --requirement requirements.txt
 - pip install .
 - pip list

#------------------------------------------------------------------------
# test runner
#------------------------------------------------------------------------

script:
 - futurize --write --stage1 . &> /dev/null
 # - futurize --write --stage2 .
 - autoflake --in-place --remove-duplicate-keys $(find . -name '*.py')
 - pyupgrade --keep-percent-format $(find . -name '*.py')
 - isort --apply --recursive .
 # - black .
 # - flake8 .
 - git diff --exit-code
 - python --version | grep "Python 3" && futurize --write --stage2 . &> /dev/null || true
 - mkdir -p build
 - cd build
 - py.test --cov-report xml --cov=pymtl3 .. $CONFIG

#-------------------------------------------------------------------------
# after success
#-------------------------------------------------------------------------

after_success:
  - codecov
